version: '2'

services:

  influxdb:
    image: influxdb:1.8.3  
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
    volumes:
      - ./data_influxdb:/var/lib/influxdb

  telegraf:
    image: telegraf:1.16.3   
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana:7.3.7     
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    #user: "0"
    links:
      - influxdb
    volumes:
      - ./data_grafana:/var/lib/grafana

volumes:
  data_influxdb:
  data_grafana:
  telegraf.conf:
